version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - uploads:/app/uploads
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672
      - REQRES_API_URL=https://reqres.in
      - UPLOAD_DIR=/app/uploads
    command: start:dev

volumes:
  mongo-data:
  uploads:
