version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_e2e
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_e2e
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app_e2e
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672
    command: test:e2e
